#!/usr/bin/env python

import httplib, urllib

params = urllib.urlencode({'hello': 'world'})
headers = {'Content-type': 'application/x-www-form-urlencoded',
			'Accept': 'text/plain'}

conn = httplib.HTTPConnection('192.168.122.254:80')
conn.request('POST', '/artifacts', params, headers)

response = conn.getresponse()
print response.status, response.reason
data = response.read()
conn.close()
