# Restart all Morph instances on a Baserock distbuild network.
#
# This will abort any running builds.
#
# This is an Ansible playbook. Run with:
#
#   ansible-playbook -i distbuild-hosts restart.yaml
#
# You will need a file named 'distbuild-hosts' describing your distbuild
# network.
---

# The order in which the processes are restarted is important! (Sadly).
- hosts: controller
  gather_facts: false
  tasks:
    - name: restart controller processes
      service: name={{ item }} state=restarted
      with_items:
        - morph-controller.service
        - morph-controller-helper.service

- hosts: workers
  gather_facts: false
  tasks:
    - name: restart worker processes
      service: name={{ item }} state=restarted
      with_items:
        - morph-worker.service
        - morph-worker-helper.service
