# Upgrade the version of Morph used on a Baserock distbuild network.
#
# This allows quickly testing a new version of Morph without having to fully
# build and deploy a new Baserock 'build' system. You should run the
# 'restart.yaml' playbook after this one.
#
# This is an Ansible playbook. Run with:
#
#   ansible-playbook -i distbuild-hosts use-latest-morph.yaml
#
# You will need a file named 'distbuild-hosts' describing your distbuild
# network.

---
- hosts: all
  gather_facts: false
  vars:
    - TROVE_HOST: git.baserock.org
    - MORPH_VERSION: sam/distbuild-build-logs
  tasks:
    - name: check out Morph from Git
      git: dest=/srv/morph version={{ MORPH_VERSION }} repo=git://{{ TROVE_HOST }}/baserock/baserock/morph accept_hostkey=True

    - name: ensure latest Morph is used
      template: backup=yes src=run-from-morph-source-tree.sh.template dest=/usr/bin/{{ item }} mode=0755
      with_items:
        - morph
        - distbuild-helper
